blueprint:
  name: Room lights - door + night mode + optional occupancy (fixed)
  description: >
    Door opens -> lights on (night_mode brightness).
    Door closes -> turn off after delay; if occupancy sensors exist, keep on until empty.
    Door left open -> notify + turn off only if empty.
  domain: automation

  input:
    door_sensor:
      name: Door sensor
      selector:
        entity:
          domain: binary_sensor

    lights_target:
      name: Lights to control
      selector:
        target:
          entity:
            domain: light

    occupancy_sensors:
      name: Occupancy sensors (optional)
      description: Add PIR/mmWave later. Leave empty for now.
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    night_mode:
      name: Night mode boolean
      selector:
        entity:
          domain: input_boolean

    day_brightness:
      name: Day brightness helper (%)
      selector:
        entity:
          domain: input_number

    night_brightness:
      name: Night brightness helper (%)
      selector:
        entity:
          domain: input_number

    off_delay_minutes:
      name: Turn-off delay after door closes / room becomes empty (minutes)
      selector:
        entity:
          domain: input_number

    door_open_timeout_minutes:
      name: Door open timeout before warning (minutes)
      selector:
        entity:
          domain: input_number

    transition_seconds:
      name: Transition (seconds)
      default: 1
      selector:
        number:
          min: 0
          max: 10
          step: 1
          unit_of_measurement: s

    notify_service:
      name: Notify service (optional)
      description: Example notify.mobile_app_your_phone. Leave blank to disable notifications.
      default: ""
      selector:
        text:

    notify_message:
      name: Notification message
      default: "Door has been left open."
      selector:
        text:

mode: restart

variables:
  occupancy_sensors: !input occupancy_sensors
  night_mode: !input night_mode
  day_brightness: !input day_brightness
  night_brightness: !input night_brightness
  off_delay_minutes: !input off_delay_minutes
  door_open_timeout_minutes: !input door_open_timeout_minutes
  transition_seconds: !input transition_seconds
  notify_service: !input notify_service
  notify_message: !input notify_message

  has_occupancy: >-
    {{ occupancy_sensors is not none and (occupancy_sensors | count) > 0 }}

  is_empty: >-
    {% if occupancy_sensors is none or (occupancy_sensors | count) == 0 %}
      true
    {% else %}
      {{ (expand(occupancy_sensors) | selectattr('state','eq','on') | list | count) == 0 }}
    {% endif %}

trigger:
  - platform: state
    entity_id: !input door_sensor
    to: "on"
    id: door_opened

  - platform: state
    entity_id: !input door_sensor
    to: "off"
    id: door_closed

action:
  - choose:

      # --- Door opened: turn on lights (night-aware) + start "door left open" timer
      - conditions:
          - condition: trigger
            id: door_opened
        sequence:
          - service: light.turn_on
            target: !input lights_target
            data:
              brightness_pct: >-
                {% if is_state(night_mode, 'on') %}
                  {{ states(night_brightness) | int(10) }}
                {% else %}
                  {{ states(day_brightness) | int(80) }}
                {% endif %}
              transition: "{{ transition_seconds | int(1) }}"

          # Wait X minutes; if door still open, notify.
          - delay:
              seconds: "{{ (states(door_open_timeout_minutes) | int(5)) * 60 }}"

          - condition: state
            entity_id: !input door_sensor
            state: "on"

          # Notify if configured
          - choose:
              - conditions: "{{ (notify_service | length) > 0 }}"
                sequence:
                  - service: "{{ notify_service }}"
                    data:
                      message: "{{ notify_message }}"

          # Only turn off if the room is empty (or no occupancy sensors configured)
          - condition: template
            value_template: "{{ is_empty }}"

          - service: light.turn_off
            target: !input lights_target
            data:
              transition: "{{ transition_seconds | int(1) }}"

      # --- Door closed: if occupancy configured, wait until empty; then delay; then off
      - conditions:
          - condition: trigger
            id: door_closed
        sequence:
          - choose:
              - conditions: "{{ has_occupancy }}"
                sequence:
                  - wait_template: "{{ is_empty }}"

          - delay:
              seconds: "{{ (states(off_delay_minutes) | float(0)) * 60 }}"

          # Re-check door still closed and empty
          - condition: state
            entity_id: !input door_sensor
            state: "off"

          - condition: template
            value_template: "{{ is_empty }}"

          - service: light.turn_off
            target: !input lights_target
            data:
              transition: "{{ transition_seconds | int(1) }}"
