blueprint:
  name: Room lights - door + night mode + optional occupancy (spec v0.9.8)
  description: >
    Door opens -> lights on (night_mode brightness).
    Door closes -> if no occupancy sensors: turn off immediately.
                 if occupancy sensors: turn off as soon as occupancy becomes false.
    Door left open -> after timeout: ONLY notify + turn off when room is empty and door is still open.
  domain: automation

  input:
    door_sensor:
      name: Door sensor
      selector:
        entity:
          domain: binary_sensor

    lights_target:
      name: Lights to control
      selector:
        target:
          entity:
            domain: light

    occupancy_sensors:
      name: Occupancy sensors (optional)
      description: Add PIR/mmWave later. Leave empty for now.
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    occupancy_off_delay_seconds:
      name: Occupancy off delay (seconds)
      description: Turn off when occupancy has been OFF for this long (door must be closed).
      default: 30
      selector:
        number:
          min: 0
          max: 600
          step: 5
          unit_of_measurement: s

    night_mode:
      name: Night mode boolean
      selector:
        entity:
          domain: input_boolean

    day_brightness:
      name: Day brightness helper (%)
      selector:
        entity:
          domain: input_number

    night_brightness:
      name: Night brightness helper (%)
      selector:
        entity:
          domain: input_number

    door_open_timeout_minutes:
      name: Door open timeout (minutes)
      description: Only applies while the door remains open.
      selector:
        entity:
          domain: input_number

    transition_seconds:
      name: Light transition (seconds)
      default: 1
      selector:
        number:
          min: 0
          max: 10
          step: 1
          unit_of_measurement: s

    notify_service:
      name: Notify service (optional)
      description: Example script.notify_household_when_home or notify.mobile_app_your_phone. Leave blank to disable.
      default: ""
      selector:
        text:

    notify_message:
      name: Notification message
      default: "Door is still open and the room is empty. Lights were turned off."
      selector:
        text:

mode: restart

variables:
  door_sensor: !input door_sensor
  occupancy_sensors: !input occupancy_sensors
  occupancy_off_delay_seconds: !input occupancy_off_delay_seconds
  night_mode: !input night_mode
  day_brightness: !input day_brightness
  night_brightness: !input night_brightness
  door_open_timeout_minutes: !input door_open_timeout_minutes
  transition_seconds: !input transition_seconds
  notify_service: !input notify_service
  notify_message: !input notify_message

  has_occupancy: >-
    {{ occupancy_sensors is not none and (occupancy_sensors | count) > 0 }}

trigger:
  - platform: state
    entity_id: !input door_sensor
    to: "on"
    id: door_opened

  - platform: state
    entity_id: !input door_sensor
    to: "off"
    id: door_closed

  - platform: state
    entity_id: !input occupancy_sensors
    to: "on"
    id: occupancy_on

  - platform: state
    entity_id: !input occupancy_sensors
    to: "off"
    for:
      seconds: !input occupancy_off_delay_seconds
    id: occupancy_off

action:
  - choose:

      # ---------------------------
      # Door opened: turn on lights, then handle "door left open" timeout
      # ---------------------------
      - conditions:
          - condition: trigger
            id: door_opened
        sequence:
          - service: light.turn_on
            target: !input lights_target
            data:
              brightness_pct: >-
                {% if is_state(night_mode, 'on') %}
                  {{ states(night_brightness) | int(10) }}
                {% else %}
                  {{ states(day_brightness) | int(80) }}
                {% endif %}
              transition: "{{ transition_seconds | int(1) }}"

          # Wait up to X minutes for the door to close. If it closes earlier, stop (door_closed branch will run).
          - wait_for_trigger:
              - platform: state
                entity_id: !input door_sensor
                to: "off"
            timeout:
              seconds: "{{ (states(door_open_timeout_minutes) | int(5)) * 60 }}"
            continue_on_timeout: true

          # If door closed before timeout, do nothing here.
          - condition: template
            value_template: "{{ wait.trigger is none }}"

          # Timeout happened; only proceed if the door is STILL open.
          - condition: state
            entity_id: !input door_sensor
            state: "on"

          # If we have occupancy sensors, wait until empty OR door closes (no notify while occupied).
          - choose:
              - conditions: "{{ has_occupancy }}"
                sequence:
                  - choose:
                      # If already empty, no waiting needed
                      - conditions: >-
                          {% set ids = occupancy_sensors if occupancy_sensors is not none else [] %}
                          {% set occ_on = expand(ids) | selectattr('state','eq','on') | list | count %}
                          {{ occ_on == 0 }}
                        sequence: []
                    default:
                      - wait_template: >-
                          {% set ids = occupancy_sensors if occupancy_sensors is not none else [] %}
                          {% set occ_on = expand(ids) | selectattr('state','eq','on') | list | count %}
                          {{ occ_on == 0 or is_state(door_sensor, 'off') }}

          # Now only act if door STILL open AND room is empty
          - condition: template
            value_template: >-
              {% if not has_occupancy %}
                {{ is_state(door_sensor, 'on') }}
              {% else %}
                {% set ids = occupancy_sensors if occupancy_sensors is not none else [] %}
                {% set occ_on = expand(ids) | selectattr('state','eq','on') | list | count %}
                {{ is_state(door_sensor, 'on') and occ_on == 0 }}
              {% endif %}


          - choose:
              - conditions: "{{ (notify_service | length) > 0 }}"
                sequence:
                  - service: "{{ notify_service }}"
                    data:
                      message: "{{ notify_message }}"
                    continue_on_error: true

          - service: light.turn_off
            target: !input lights_target
            data:
              transition: "{{ transition_seconds | int(1) }}"

      # ---------------------------
      # Occupancy detected: re-light if door is closed
      # ---------------------------
      - conditions:
          - condition: trigger
            id: occupancy_on
        sequence:
          - service: light.turn_on
            target: !input lights_target
            data:
              brightness_pct: >-
                {% if is_state(night_mode, 'on') %}
                  {{ states(night_brightness) | int(10) }}
                {% else %}
                  {{ states(day_brightness) | int(80) }}
                {% endif %}
              transition: "{{ transition_seconds | int(1) }}"

      # ---------------------------
      # Occupancy cleared: if door is closed and ALL occupancy sensors are off -> turn off lights
      # ---------------------------
      - conditions:
          - condition: trigger
            id: occupancy_off
          - condition: state
            entity_id: !input door_sensor
            state: "off"  # door closed
          - condition: template
            value_template: >-
              {% set ids = occupancy_sensors if occupancy_sensors is not none else [] %}
              {{ (expand(ids) | selectattr('state','eq','on') | list | count) == 0 }}
        sequence:
          - service: light.turn_off
            target: !input lights_target
            data:
              transition: "{{ transition_seconds | int(1) }}"

      # ---------------------------
      # Door closed: turn off immediately if no occupancy.
      # If occupancy exists: turn off as soon as occupancy becomes false.
      # ---------------------------
      - conditions:
          - condition: trigger
            id: door_closed
        sequence:
          - choose:
              - conditions: "{{ has_occupancy }}"
                sequence:
                  # If already empty, turn off immediately; otherwise wait until empty then off
                  - choose:
                      - conditions: >-
                          {% set ids = occupancy_sensors if occupancy_sensors is not none else [] %}
                          {% set occ_on = expand(ids) | selectattr('state','eq','on') | list | count %}
                          {{ occ_on == 0 }}
                        sequence: []
                    default:
                      - wait_template: >-
                          {% set ids = occupancy_sensors if occupancy_sensors is not none else [] %}
                          {% set occ_on = expand(ids) | selectattr('state','eq','on') | list | count %}
                          {{ occ_on == 0 }}
                  - service: light.turn_off
                    target: !input lights_target
                    data:
                      transition: "{{ transition_seconds | int(1) }}"
            default:
              - service: light.turn_off
                target: !input lights_target
                data:
                  transition: "{{ transition_seconds | int(1) }}"