blueprint:
  name: "Hue Remote V2 - Mode/Variant (Z2M MQTT device triggers, Area + Labels) v0.4.3"
  description: >
    Uses MQTT device triggers discovered via Zigbee2MQTT (type: action, subtype: on_press/off_press/up_press/down_press).
    - on_press: toggle (if lights on -> turn off + reset defaults; if off -> set defaults + apply scene)
    - off_press: cycle variant (Hue button)
    - up_press/down_press: change mode (no cycling) and reset variant to 1
    Default mode comes from a global input_select (e.g. input_select.hemmalage).
  domain: automation

  input:
    remote_device:
      name: "Remote device"
      description: "Select the Zigbee2MQTT remote device"
      selector:
        device:
          integration: mqtt
          multiple: false

    target_area:
      name: "Target area (room)"
      selector:
        area: {}

    mode_helper:
      name: "Room mode helper (input_select: Dag/Morgon/Kv채ll/Natt)"
      selector:
        entity:
          domain: input_select

    variant_helper:
      name: "Room variant helper (input_number)"
      selector:
        entity:
          domain: input_number

    global_mode_helper:
      name: "Global mode helper (input_select, e.g. hemmalage)"
      description: "Your global source-of-truth mode (Dag/Morgon/Kv채ll/Natt)"
      selector:
        entity:
          domain: input_select

    default_variant:
      name: "Default variant when (re)starting"
      default: 1
      selector:
        number:
          min: 1
          max: 10
          step: 1
          mode: box

    transition:
      name: "Scene transition (seconds)"
      default: 0.4
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          mode: box

mode: single

trigger:
  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: on_press
    id: on_press

  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: off_press
    id: off_press

  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: up_press
    id: up_press

  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: down_press
    id: down_press

variables:
  area_id: !input target_area
  area_name: "{{ area_name(area_id) }}"
  mode_helper: !input mode_helper
  variant_helper: !input variant_helper
  global_mode_helper: !input global_mode_helper
  default_variant: !input default_variant
  transition: !input transition

  any_lights_on: >-
    {% set lights = area_entities(area_id) | select('match', '^light\\.') | list %}
    {{ (expand(lights) | selectattr('state','eq','on') | list | count) > 0 }}

  # Default mode now comes directly from the global input_select
  default_mode: >-
    {% set m = states(global_mode_helper) %}
    {% if m in ['Dag','Twilight','Natt','Morgon','Kv채ll'] %}
      {{ m }}
    {% else %}
      Dag
    {% endif %}

action:
  - choose:
      # on_press = TOGGLE
      - conditions: "{{ trigger.id == 'on_press' }}"
        sequence:
          - choose:
              # If lights are on -> off + reset defaults
              - conditions: "{{ any_lights_on }}"
                sequence:
                  - service: light.turn_off
                    target:
                      area_id: "{{ area_id }}"
                  - service: input_select.select_option
                    target:
                      entity_id: "{{ mode_helper }}"
                    data:
                      option: "{{ default_mode }}"
                  - service: input_number.set_value
                    target:
                      entity_id: "{{ variant_helper }}"
                    data:
                      value: "{{ default_variant }}"

              # If lights are off -> set defaults + apply selection
              - conditions: "{{ not any_lights_on }}"
                sequence:
                  - service: input_select.select_option
                    target:
                      entity_id: "{{ mode_helper }}"
                    data:
                      option: "{{ default_mode }}"
                  - service: input_number.set_value
                    target:
                      entity_id: "{{ variant_helper }}"
                    data:
                      value: "{{ default_variant }}"
                  - service: script.apply_mode_variant_scene_for_area
                    data:
                      area_name: "{{ area_name }}"
                      mode_helper: "{{ mode_helper }}"
                      variant_helper: "{{ variant_helper }}"
                      transition: "{{ transition }}"

      # off_press = Hue button = cycle variant (wrap)
      - conditions: "{{ trigger.id == 'off_press' }}"
        sequence:
          - variables:
              mode: "{{ states(mode_helper) }}"
              h: "{{ now().hour }}"
              effective_mode: >-
                {% if mode == 'Twilight' %}
                  {% if h >= 6 and h < 12 %}
                    Morgon
                  {% else %}
                    Kv채ll
                  {% endif %}
                {% else %}
                  {{ mode }}
                {% endif %}
              scenes: >-
                {{
                  area_entities(area_id)
                  | select('in', label_entities(effective_mode))
                  | select('match', '^scene\\.')
                  | list
                  | sort
                }}
              maxv: "{{ scenes | length }}"
              v: "{{ states(variant_helper) | int(1) }}"
              next_v: "{{ 1 if maxv < 1 else ((v % maxv) + 1) }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ variant_helper }}"
            data:
              value: "{{ next_v }}"
          - choose:
              - conditions: "{{ any_lights_on }}"
                sequence:
                  - service: script.apply_mode_variant_scene_for_area
                    data:
                      area_name: "{{ area_name }}"
                      mode_helper: "{{ mode_helper }}"
                      variant_helper: "{{ variant_helper }}"
                      transition: "{{ transition }}"

      # up_press = brighter mode (no cycling at ends) + variant=1
      - conditions: "{{ trigger.id == 'up_press' }}"
        sequence:
          - variables:
              order: ["Natt", "Twilight", "Dag"]
              cur: "{{ states(mode_helper) }}"
              idx: "{{ order.index(cur) if cur in order else 0 }}"
              new_idx: "{{ [idx + 1, (order | length) - 1] | min }}"
              new_mode: "{{ order[new_idx] }}"
          - service: input_select.select_option
            target:
              entity_id: "{{ mode_helper }}"
            data:
              option: "{{ new_mode }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ variant_helper }}"
            data:
              value: 1
          - choose:
              - conditions: "{{ any_lights_on }}"
                sequence:
                  - service: script.apply_mode_variant_scene_for_area
                    data:
                      area_name: "{{ area_name }}"
                      mode_helper: "{{ mode_helper }}"
                      variant_helper: "{{ variant_helper }}"
                      transition: "{{ transition }}"

      # down_press = dimmer mode (no cycling at ends) + variant=1
      - conditions: "{{ trigger.id == 'down_press' }}"
        sequence:
          - variables:
              order: ["Natt", "Twilight", "Dag"]
              cur: "{{ states(mode_helper) }}"
              idx: "{{ order.index(cur) if cur in order else 0 }}"
              new_idx: "{{ [idx - 1, 0] | max }}"
              new_mode: "{{ order[new_idx] }}"
          - service: input_select.select_option
            target:
              entity_id: "{{ mode_helper }}"
            data:
              option: "{{ new_mode }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ variant_helper }}"
            data:
              value: 1
          - choose:
              - conditions: "{{ any_lights_on }}"
                sequence:
                  - service: script.apply_mode_variant_scene_for_area
                    data:
                      area_name: "{{ area_name }}"
                      mode_helper: "{{ mode_helper }}"
                      variant_helper: "{{ variant_helper }}"
                      transition: "{{ transition }}"
