blueprint:
  name: Hue Remote V2 - Mode/Variant scenes via Z2M MQTT (Area + Labels)
  description: >
    Uses Zigbee2MQTT MQTT action payloads (on_press/off_press/up_press/down_press)
    to control scenes by Mode (Dag/Kväll/Natt) + Variant (01/02/03...).
    - on_press: toggle (if lights on -> off + reset, else -> set defaults + apply scene)
    - off_press: cycle variant (Hue button)
    - up_press/down_press: change mode (no cycling) and reset variant to 1
    Defaults come from global helpers: nattläge > kvällsläge > Dag.
  domain: automation

  input:
    mqtt_topic:
      name: Zigbee2MQTT topic for the remote
      description: "Usually: zigbee2mqtt/<friendly_name>"
      selector:
        text: {}

    target_area:
      name: Target area (room)
      selector:
        area: {}

    mode_helper:
      name: "Room mode helper (input_select Dag/Kväll/Natt)"
      selector:
        entity:
          domain: input_select

    variant_helper:
      name: Room variant helper (input_number)
      selector:
        entity:
          domain: input_number

    evening_flag:
      name: Global 'Kvällsläge' flag
      description: "input_boolean or binary_sensor. 'on' means evening mode active."
      selector:
        entity: {}

    night_flag:
      name: Global 'Nattläge' flag
      description: "input_boolean or binary_sensor. 'on' means night mode active."
      selector:
        entity: {}

    default_variant:
      name: Default variant when (re)starting
      default: 1
      selector:
        number:
          min: 1
          max: 10
          step: 1
          mode: box

    transition:
      name: Scene transition (seconds)
      default: 0.4
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          mode: box

mode: single

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

variables:
  area_id: !input target_area
  area_name: "{{ area_name(area_id) }}"
  mode_helper: !input mode_helper
  variant_helper: !input variant_helper
  evening_flag: !input evening_flag
  night_flag: !input night_flag
  default_variant: !input default_variant
  transition: !input transition

  # Z2M sends JSON with {"action":"on_press"} etc.
  act: >-
    {% set p = trigger.payload_json %}
    {% if p is mapping and 'action' in p %}
      {{ p.action }}
    {% else %}
      {{ trigger.payload }}
    {% endif %}

  # Any light on in the area?
  any_lights_on: >-
    {% set lights = area_entities(area_id) | select('match', '^light\\.') | list %}
    {{ (expand(lights) | selectattr('state','eq','on') | list | count) > 0 }}

  # Default mode from your global flags
  default_mode: >-
    {% if is_state(night_flag, 'on') %}
      Natt
    {% elif is_state(evening_flag, 'on') %}
      Kväll
    {% else %}
      Dag
    {% endif %}

action:
  - choose:
      # on_press = TOGGLE
      - conditions: "{{ act == 'on_press' }}"
        sequence:
          - choose:
              # If on -> turn off + reset to defaults
              - conditions: "{{ any_lights_on }}"
                sequence:
                  - service: light.turn_off
                    target:
                      area_id: "{{ area_id }}"
                  - service: input_select.select_option
                    target:
                      entity_id: "{{ mode_helper }}"
                    data:
                      option: "{{ default_mode }}"
                  - service: input_number.set_value
                    target:
                      entity_id: "{{ variant_helper }}"
                    data:
                      value: "{{ default_variant }}"

              # If off -> set defaults + apply scene (turns lights on via scene)
              - conditions: "{{ not any_lights_on }}"
                sequence:
                  - service: input_select.select_option
                    target:
                      entity_id: "{{ mode_helper }}"
                    data:
                      option: "{{ default_mode }}"
                  - service: input_number.set_value
                    target:
                      entity_id: "{{ variant_helper }}"
                    data:
                      value: "{{ default_variant }}"
                  - service: script.apply_mode_variant_scene_for_area
                    data:
                      area_name: "{{ area_name }}"
                      mode_helper: "{{ mode_helper }}"
                      variant_helper: "{{ variant_helper }}"
                      transition: "{{ transition }}"

      # off_press (Hue button) = cycle variant within current mode (wrap)
      - conditions: "{{ act == 'off_press' }}"
        sequence:
          - variables:
              mode: "{{ states(mode_helper) }}"
              scenes: >-
                {{
                  area_entities(area_id)
                  | select('in', label_entities(mode))
                  | select('match', '^scene\\.')
                  | list
                  | sort
                }}
              maxv: "{{ scenes | length }}"
              v: "{{ states(variant_helper) | int(1) }}"
              next_v: "{{ 1 if maxv < 1 else ((v % maxv) + 1) }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ variant_helper }}"
            data:
              value: "{{ next_v }}"
          - choose:
              - conditions: "{{ any_lights_on }}"
                sequence:
                  - service: script.apply_mode_variant_scene_for_area
                    data:
                      area_name: "{{ area_name }}"
                      mode_helper: "{{ mode_helper }}"
                      variant_helper: "{{ variant_helper }}"
                      transition: "{{ transition }}"

      # up_press = brighter mode (no cycling)
      - conditions: "{{ act == 'up_press' }}"
        sequence:
          - variables:
              order: ["Natt", "Kväll", "Dag"]  # dimmest -> brightest
              cur: "{{ states(mode_helper) }}"
              idx: "{{ order.index(cur) if cur in order else 0 }}"
              new_idx: "{{ [idx + 1, (order | length) - 1] | min }}"
              new_mode: "{{ order[new_idx] }}"
          - service: input_select.select_option
            target:
              entity_id: "{{ mode_helper }}"
            data:
              option: "{{ new_mode }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ variant_helper }}"
            data:
              value: 1
          - choose:
              - conditions: "{{ any_lights_on }}"
                sequence:
                  - service: script.apply_mode_variant_scene_for_area
                    data:
                      area_name: "{{ area_name }}"
                      mode_helper: "{{ mode_helper }}"
                      variant_helper: "{{ variant_helper }}"
                      transition: "{{ transition }}"

      # down_press = dimmer mode (no cycling)
      - conditions: "{{ act == 'down_press' }}"
        sequence:
          - variables:
              order: ["Natt", "Kväll", "Dag"]
              cur: "{{ states(mode_helper) }}"
              idx: "{{ order.index(cur) if cur in order else 0 }}"
              new_idx: "{{ [idx - 1, 0] | max }}"
              new_mode: "{{ order[new_idx] }}"
          - service: input_select.select_option
            target:
              entity_id: "{{ mode_helper }}"
            data:
              option: "{{ new_mode }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ variant_helper }}"
            data:
              value: 1
          - choose:
              - conditions: "{{ any_lights_on }}"
                sequence:
                  - service: script.apply_mode_variant_scene_for_area
                    data:
                      area_name: "{{ area_name }}"
                      mode_helper: "{{ mode_helper }}"
                      variant_helper: "{{ variant_helper }}"
                      transition: "{{ transition }}"
